
import React, { useState } from 'react';
import { scrapeWhopListing } from './services/gemini';
import { WhopListing, ScrapingState } from './types';
import ListingCard from './components/ListingCard';

const App: React.FC = () => {
  const [input, setInput] = useState('');
  const [state, setState] = useState<ScrapingState>({
    isLoading: false,
    error: null,
    history: [],
    currentResult: null,
  });

  const handleScrape = async (e?: React.FormEvent) => {
    if (e) e.preventDefault();
    if (!input.trim()) return;

    setState(prev => ({ ...prev, isLoading: true, error: null }));

    try {
      const data = await scrapeWhopListing(input);
      setState(prev => ({
        ...prev,
        isLoading: false,
        currentResult: data,
        history: [data, ...prev.history.filter(h => h.name !== data.name)].slice(0, 10),
      }));
      setInput('');
    } catch (err: any) {
      setState(prev => ({
        ...prev,
        isLoading: false,
        error: err.message || 'Intelligence engine stalled. Try a different hub name.',
      }));
    }
  };

  const selectFromHistory = (listing: WhopListing) => {
    setState(prev => ({ ...prev, currentResult: listing }));
  };

  const exportReport = (listing: WhopListing) => {
    const report = `
# WHOP INTEL REPORT: ${listing.name}
Extracted at: ${new Date(listing.extractedAt).toLocaleString()}
---

## Description
${listing.description}

## Pricing Plans
${listing.plans.map(p => `- ${p.name}: ${p.currency}${p.price} (${p.cycle})`).join('\n')}

## Core Features
${listing.features.map(f => `- ${f}`).join('\n')}

## Sentiment Analysis
Global Score: ${listing.sentimentScore}/10
- Value for Money: ${listing.sentimentBreakdown.valueForMoney}%
- Quality: ${listing.sentimentBreakdown.quality}%
- Support: ${listing.sentimentBreakdown.support}%
- Ease of Use: ${listing.sentimentBreakdown.easeOfUse}%

### Pros
${listing.pros.map(p => `- ${p}`).join('\n')}

### Cons
${listing.cons.map(c => `- ${c}`).join('\n')}

## Competition & Market
Growth Potential: ${listing.growthPotential}

### Key Competitors
${listing.competitors.map(c => `- ${c.name} (${c.priceRange}): ${c.advantage}`).join('\n')}

---
Intelligence generated by WhopScan AI.
    `.trim();

    const blob = new Blob([report], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `WhopIntel_${listing.name.replace(/\s+/g, '_')}.md`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="min-h-screen bg-[#020617] text-slate-100 selection:bg-indigo-500/30 font-sans">
      {/* Dynamic Background */}
      <div className="fixed inset-0 pointer-events-none overflow-hidden z-0">
        <div className="absolute top-[-20%] left-[-10%] w-[60%] h-[60%] bg-indigo-600/10 blur-[150px] rounded-full animate-pulse opacity-40"></div>
        <div className="absolute bottom-[-20%] right-[-10%] w-[60%] h-[60%] bg-purple-600/10 blur-[150px] rounded-full animate-pulse delay-700 opacity-40"></div>
      </div>

      <nav className="sticky top-0 z-50 glass-morphism border-b border-white/5 backdrop-blur-2xl">
        <div className="max-w-7xl mx-auto px-6 h-20 flex items-center justify-between">
          <div className="flex items-center gap-4 group cursor-pointer">
            <div className="relative">
              <div className="absolute inset-0 bg-indigo-500 blur-lg opacity-40 group-hover:opacity-70 transition-opacity"></div>
              <div className="relative w-11 h-11 bg-gradient-to-br from-indigo-500 to-purple-600 rounded-2xl flex items-center justify-center shadow-2xl border border-white/20 transform group-hover:rotate-12 transition-transform">
                <i className="fa-solid fa-radar text-white text-xl"></i>
              </div>
            </div>
            <div>
              <h1 className="text-2xl font-black tracking-tighter text-white">WHOP<span className="text-indigo-500">SCAN</span></h1>
              <div className="flex items-center gap-2">
                <span className="text-[9px] font-black text-indigo-400 uppercase tracking-[0.3em]">AI-INTEL TERMINAL</span>
                <span className="w-1 h-1 rounded-full bg-slate-700"></span>
                <span className="text-[9px] font-bold text-slate-500 uppercase tracking-widest">v2.1</span>
              </div>
            </div>
          </div>
          
          <div className="hidden md:flex items-center gap-6">
             <div className="flex -space-x-2">
                {[1,2,3].map(i => (
                  <div key={i} className="w-8 h-8 rounded-full border-2 border-slate-900 bg-slate-800 flex items-center justify-center overflow-hidden">
                    <img src={`https://api.dicebear.com/7.x/identicon/svg?seed=${i + 123}`} alt="user" />
                  </div>
                ))}
             </div>
             <p className="text-[10px] font-bold text-slate-400 uppercase tracking-widest">Active Analysis Sessions</p>
          </div>
        </div>
      </nav>

      <main className="relative z-10 max-w-7xl mx-auto px-6 mt-12 grid grid-cols-1 lg:grid-cols-12 gap-10">
        
        {/* Sidebar */}
        <div className="lg:col-span-4 space-y-8">
          <section className="glass-morphism rounded-[40px] p-8 md:p-10 border border-white/10 shadow-3xl bg-white/2">
            <h2 className="text-xs font-black text-slate-500 uppercase tracking-[0.4em] mb-8">Target Input</h2>
            
            <form onSubmit={handleScrape} className="space-y-6">
              <div className="relative group">
                <div className="absolute -inset-1 bg-gradient-to-r from-indigo-500 to-purple-600 rounded-3xl blur opacity-10 group-focus-within:opacity-40 transition-opacity"></div>
                <input
                  type="text"
                  value={input}
                  onChange={(e) => setInput(e.target.value)}
                  placeholder="URL or Product Name..."
                  className="relative w-full bg-[#0a0f1e]/80 border border-white/10 rounded-2xl px-6 py-5 text-sm focus:outline-none focus:ring-1 focus:ring-white/20 transition-all text-white placeholder:text-slate-600 font-medium"
                />
                <button
                  type="submit"
                  disabled={state.isLoading}
                  className="absolute right-3 top-3 bottom-3 bg-white text-black hover:bg-indigo-400 hover:text-white disabled:bg-slate-800 disabled:text-slate-500 px-6 rounded-xl transition-all shadow-xl active:scale-95 flex items-center gap-2 text-xs font-black uppercase tracking-wider"
                >
                  {state.isLoading ? (
                    <i className="fa-solid fa-dna fa-spin"></i>
                  ) : (
                    <i className="fa-solid fa-bolt"></i>
                  )}
                  {state.isLoading ? 'Processing' : 'Analyze'}
                </button>
              </div>
              
              <div className="p-5 bg-white/2 rounded-2xl border border-white/5 space-y-3">
                <p className="text-[10px] font-black text-indigo-400 uppercase tracking-widest">Global Scan Capabilities</p>
                <div className="grid grid-cols-2 gap-2">
                  {['Pricing', 'Tiers', 'Competitors', 'Sentiment'].map(t => (
                    <div key={t} className="flex items-center gap-2 text-[10px] text-slate-500 font-bold">
                      <i className="fa-solid fa-circle-check text-indigo-500/50"></i>
                      {t}
                    </div>
                  ))}
                </div>
              </div>
            </form>

            {state.error && (
              <div className="mt-8 p-5 bg-red-500/10 border border-red-500/20 rounded-2xl text-red-400 text-xs flex items-start gap-4 animate-in fade-in slide-in-from-top-4">
                <div className="w-8 h-8 rounded-lg bg-red-500/20 flex items-center justify-center flex-shrink-0">
                  <i className="fa-solid fa-triangle-exclamation"></i>
                </div>
                <div>
                   <p className="font-black uppercase tracking-wider mb-1">System Error</p>
                   <p className="font-medium opacity-80 leading-relaxed">{state.error}</p>
                </div>
              </div>
            )}
          </section>

          <section>
            <div className="flex items-center justify-between mb-6 px-4">
              <h3 className="text-[10px] font-black text-slate-500 uppercase tracking-[0.4em]">Historical Intel</h3>
              <div className="h-[1px] flex-1 mx-4 bg-white/5"></div>
              <span className="text-[9px] font-black text-slate-400 bg-white/5 px-2 py-1 rounded-md">{state.history.length}</span>
            </div>
            
            <div className="space-y-4">
              {state.history.length === 0 ? (
                <div className="py-16 flex flex-col items-center justify-center glass-morphism rounded-[40px] border border-dashed border-white/5 bg-white/1">
                  <div className="w-12 h-12 rounded-full bg-slate-900 border border-white/5 flex items-center justify-center mb-4">
                    <i className="fa-solid fa-history text-slate-700"></i>
                  </div>
                  <p className="text-slate-600 text-[10px] font-black uppercase tracking-widest">No Recent Scans</p>
                </div>
              ) : (
                state.history.map((item) => (
                  <button
                    key={item.id}
                    onClick={() => selectFromHistory(item)}
                    className={`group w-full text-left p-5 rounded-3xl border transition-all duration-300 flex items-center justify-between relative overflow-hidden ${
                      state.currentResult?.id === item.id 
                        ? 'bg-indigo-600/10 border-indigo-500/50 shadow-lg shadow-indigo-500/5' 
                        : 'bg-white/1 border-white/5 hover:border-white/10 hover:bg-white/2'
                    }`}
                  >
                    <div className="flex-1 min-w-0 pr-4 relative z-10">
                      <h4 className="text-xs font-black text-slate-200 group-hover:text-white truncate mb-1 uppercase tracking-wider">
                        {item.name}
                      </h4>
                      <div className="flex items-center gap-2">
                        <span className="text-[8px] bg-slate-800 text-slate-500 px-1.5 py-0.5 rounded-sm font-black uppercase tracking-widest">{item.category}</span>
                        <span className="text-[8px] text-slate-600 font-bold uppercase">
                          {new Date(item.extractedAt).toLocaleDateString()}
                        </span>
                      </div>
                    </div>
                    <div className="text-right relative z-10">
                      <p className="text-xs font-black text-indigo-400">{item.plans[0]?.currency}{item.plans[0]?.price}</p>
                      <p className="text-[8px] text-slate-600 font-black uppercase tracking-widest">Entry Tier</p>
                    </div>
                    {state.currentResult?.id === item.id && (
                      <div className="absolute left-0 top-0 bottom-0 w-1 bg-indigo-500 shadow-[0_0_15px_rgba(99,102,241,0.5)]"></div>
                    )}
                  </button>
                ))
              )}
            </div>
          </section>
        </div>

        {/* Intelligence Desktop */}
        <div className="lg:col-span-8">
          {state.isLoading ? (
            <div className="space-y-8 animate-pulse">
              <div className="glass-morphism rounded-[40px] p-12 space-y-10 border border-white/10 bg-white/2">
                <div className="flex justify-between items-center">
                  <div className="h-12 w-1/2 bg-white/5 rounded-2xl"></div>
                  <div className="h-12 w-32 bg-white/5 rounded-2xl"></div>
                </div>
                <div className="h-40 w-full bg-white/5 rounded-[32px]"></div>
                <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
                  <div className="h-72 bg-white/5 rounded-[32px]"></div>
                  <div className="h-72 bg-white/5 rounded-[32px]"></div>
                </div>
              </div>
              <div className="flex flex-col items-center justify-center py-10 gap-6">
                <div className="relative">
                   <div className="w-16 h-16 border-4 border-indigo-500/20 border-t-indigo-500 rounded-full animate-spin"></div>
                   <i className="fa-solid fa-satellite-dish absolute inset-0 m-auto w-fit h-fit text-indigo-400"></i>
                </div>
                <div className="text-center space-y-2">
                  <h3 className="text-indigo-400 text-sm font-black uppercase tracking-[0.5em] animate-pulse">
                    Scanning Ecosystem
                  </h3>
                  <p className="text-slate-600 text-[10px] font-black uppercase tracking-widest">Deconstructing marketplace benchmarks...</p>
                </div>
              </div>
            </div>
          ) : state.currentResult ? (
            <ListingCard listing={state.currentResult} onExport={exportReport} />
          ) : (
            <div className="h-[700px] glass-morphism rounded-[60px] border border-dashed border-white/5 flex flex-col items-center justify-center p-12 text-center group bg-white/[0.01]">
              <div className="relative mb-12">
                <div className="absolute inset-0 bg-indigo-500 blur-[100px] opacity-10 group-hover:opacity-20 transition-all duration-700"></div>
                <div className="relative w-32 h-32 bg-[#0a0f1e] rounded-[40px] flex items-center justify-center border border-white/10 shadow-3xl transform group-hover:scale-105 transition-transform">
                   <div className="absolute inset-2 border border-indigo-500/20 rounded-[32px] animate-pulse"></div>
                   <i className="fa-solid fa-compass text-indigo-500 text-5xl animate-spin-slow"></i>
                </div>
              </div>
              <h3 className="text-3xl font-black text-white mb-6 tracking-tighter">Market Readiness: <span className="text-indigo-500">STANDBY</span></h3>
              <p className="text-slate-500 max-w-lg text-sm font-medium leading-relaxed mb-12">
                Target a Whop community, SaaS product, or trading hub for deep-dive intelligence. We use multi-agent search grounding to build a 360° market profile.
              </p>
              
              <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6 w-full max-w-2xl">
                {[
                  { icon: 'fa-chart-pie', label: 'Pricing Engine', color: 'text-indigo-400' },
                  { icon: 'fa-users-rays', label: 'Sentiment Map', color: 'text-emerald-400' },
                  { icon: 'fa-microchip', label: 'Feature Stack', color: 'text-purple-400' }
                ].map((feature, i) => (
                  <div key={i} className="bg-white/2 p-6 rounded-[32px] border border-white/5 hover:border-white/10 transition-all">
                    <i className={`fa-solid ${feature.icon} ${feature.color} text-xl mb-4`}></i>
                    <p className="text-[10px] font-black text-white uppercase tracking-widest">{feature.label}</p>
                  </div>
                ))}
              </div>
            </div>
          )}
        </div>
      </main>

      <footer className="mt-40 pb-20 flex flex-col items-center gap-6">
        <div className="h-[1px] w-32 bg-gradient-to-r from-transparent via-white/10 to-transparent"></div>
        <div className="flex items-center gap-8">
          <p className="text-[10px] text-slate-600 font-black uppercase tracking-[0.5em]">Enterprise Terminal</p>
          <p className="text-[10px] text-indigo-500/50 font-black uppercase tracking-[0.5em]">Grounding Active</p>
          <p className="text-[10px] text-slate-600 font-black uppercase tracking-[0.5em]">Auth: Gemini 3.0</p>
        </div>
      </footer>
    </div>
  );
};

export default App;
